### PR TITLE
fix: start ganache command when invoked from the command palette

### LINKED ISSUE #138: Fix `Truffle: Start Ganache` command when invoked from the command palette
The `Truffle: Start Ganache` command (linked to **`truffle-vscode.startGanacheServer`** command id) raises a `Cannot start ganache server` error when invoked directly from the command palette. It actually displays a picker to allow the user to select the service to be started.

truffle-sample-project-1657638940552

Moreover, when the user selects `Truffle: Restart Ganache`, the pickers appears twice before failing with same error.

truffle-sample-project-1657715317489

On the other hand, when invoked within the `Truffle/Networks` view, it works correctly.

truffle-sample-project-1657639147281

### PR DESCRIPTION
**Pull request by acuarica**
Closes #138.

### CODE REVIEW

File: src/commands/GanacheCommands.ts [hunk 1]
```diff
@@ -56,11 +90,23 @@ export namespace GanacheCommands {
...
+  /**
+   * Gets or selects the Ganache port and options that can be used to start or stop a Ganache process.
+   * If `projectView` is present, it returns the `port` and `options` from that `projectView`.
+   * Otherwise, it displays a `window.showQuickPick` to allow the user
+   * to select a Ganache server to start or stop.
+   *
+   * @param projectView the tree item from the _Networks_ view to get `port` and `options`, if any.
+   * @returns a promise that resolves to a `port` and `options`.
+   */
+  export async function selectGanachePortAndOptions(projectView?: ProjectView): Promise<GanachePortAndOptions> {
```
Comment (xhulz) [inline src/commands/GanacheCommands.ts:106]: Much better to have combined these two functions :)

File: src/commands/GanacheCommands.ts [hunk 2]
```diff
@@ -12,8 +12,32 @@ import {Telemetry} from '../TelemetryClient';
...
+   * Starts a new Ganache server using the `ganacheConfigSelector`.
+   * The `ganacheConfigSelector` resolves to the `port` and `options`
+   * used to start a new Ganache process.
+   * The selector must be lazy since `startGanacheCmd` needs to first check
+   * whether some required apps are installed.
+   *
+   * @param ganacheConfigSelector the selector that resolves to a `port` and `options`.
+   * @returns
+   */
+  export async function startGanacheCmd(ganacheConfigSelector: () => Promise<GanachePortAndOptions>): Promise<void> {
```
Comment (xhulz) [inline src/commands/GanacheCommands.ts:40]: Maybe keep the `projectView` as the input parameter like the `stopGanacheCmd(projectView?: ProjectView): Promise<void>` function just to keep the notation, but for me it's perfect :)

**Review by xhulz — APPROVED** [review]

File: src/commands/GanacheCommands.ts (hunk 2 above)
Comment (acuarica) [reply src/commands/GanacheCommands.ts:40]: I also was keen to keep both `startGanacheCmd` and `stopGanacheCmd` with the same signature. However, they get the `projectView` in different ways, since when restarting, the `port` and `options` from `stopGanacheCmd` flows into `startGanacheCmd`.
