### PR TITLE
Fix Telemetry setup

### LINKED ISSUE #285: Review Telemetry settings and setup
Review how to enable or disable sending Telemetry events from the extension. The currently used `enableTelemetry` setting has been deprecated in favor of `telemetryLevel`[1]. We need to honor this setting and/or include our own customized setting to be in sync with the rest of Truffle products. This is according to the _Telemetry extension authors guide_[2].

Moreover, we need to update our `README.md` to reflect any changes made. The section on _Telemetry_[3] is outdated as well.

Notice that the new `telemetryLevel` setting is an enum with values `all`, `error`,`crash` and `off`. Thus we can be more specific on the event that are being logged.

We might also want to consider using the new [`@vscode/extension-telemetry`](https://www.npmjs.com/package/@vscode/extension-telemetry) package. The extension currently uses [`vscode-extension-telemetry`](https://www.npmjs.com/package/vscode-extension-telemetry) which has been deprecated. Moreover the new package seems to have out-of-the-box support for the `telemetryLevel` flag.

See https://news.ycombinator.com/item?id=28812486 and https://github.com/microsoft/vscode/issues/134660 for a background discussion.

---

- [1] https://code.visualstudio.com/docs/supporting/faq#_how-to-disable-telemetry-reporting
- [2] https://code.visualstudio.com/api/extension-guides/telemetry
- [3] https://github.com/trufflesuite/vscode-ext#telemetry

### PR DESCRIPTION
**Pull request by acuarica**
## PR description

This PR closes #285.

A couple of points to note

- The latest `0.7.3-preview` version uses a [Proposed API](https://code.visualstudio.com/api/advanced-topics/using-proposed-api) which is not suited for use. That's why we use the latest non-preview version.
- The validation of the VS Code telemetry flag [`env.isTelemetryEnabled`](https://code.visualstudio.com/api/references/vscode-api#env)/[`telemetry.telemetryLevel`](https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting) was removed since that check is embedded in the `@vscode/extension-telemetry` package.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if documentation updates are required.

### CODE REVIEW

File: src/Telemetry.ts [hunk 1]
```diff
@@ -3,52 +3,39 @@
...
-          this.defaultProperties['common.vscodesessionid'] = generateSessionId();
-        } catch (error) {
-          Output.outputLine(OutputLabel.telemetryClient, `Initialize done with error: ${(error as Error).message}`);
-        }
-      }
+    try {
+      this.reporter = new TelemetryReporter(Constants.extensionName, Constants.extensionVersion, extensionKey);
+      // set default values for machine/session ids
+      this.defaultProperties['common.vscodemachineid'] = generateMachineId();
+      this.defaultProperties['common.vscodesessionid'] = generateSessionId();
```
Comment (acuarica) [inline src/Telemetry.ts]: Any ideas why we include these two lines? AFAIU they are already provided by `@vscode/extension-telemetry`

https://github.com/microsoft/vscode-extension-telemetry/blob/04ff08da26bc437e87bfb398ac63be2685576066/src/common/baseTelemetryReporter.ts#L159-L160

Do you think is safe to remove this? @kevinbluer @xhulz @michaeljohnbennett

File: package.json [hunk 2]
```diff
@@ -88,6 +88,11 @@
           "enum": [
             "Truffle"
           ]
+        },
+        "truffle-vscode.enableTelemetry": {
+          "type": "boolean",
+          "default": true,
+          "markdownDescription": "Indicates whether to collect anonymous product usage data. Regardless of this setting, we honor the [`telemetry.telemetryLevel`](https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting) user setting, _i.e._, if `telemetry.telemetryLevel` is `off` we do not send any data regardless of this setting. See <https://trufflesuite.com/analytics/> for more info"
```
Comment (acuarica) [inline package.json]: @kevinbluer you might want to improve this `description`. Is there any other telemetry policy to mention here?

**Review by xhulz — APPROVED** [review]
LGTM
