### PR TITLE
Use `contracts_directory` from Truffle config in `Create Contract` command

### LINKED ISSUE #189: Fix `Create Contract` command when invoked from a nested folder
As @xhulz pointed out in https://github.com/trufflesuite/vscode-ext/pull/181#pullrequestreview-1060155346, the `Create Contract` command places the created contract in the wrong place when invoked from a nested folder

create-contract

### PR DESCRIPTION
**Pull request by acuarica**
Closes #189.

### CODE REVIEW

**Review by xhulz — APPROVED** [review]
LGTM

File: src/commands/TruffleCommands.ts [hunk 1]
```diff
@@ -188,12 +188,35 @@ export namespace TruffleCommands {
...
+   * @param folderUri if provided, the `Uri` to place the newly created contract.
+   */
   export async function createContract(folderUri?: Uri): Promise<void> {
-    const uri = await getTruffleWorkspace(folderUri);
-    const workspace = uri.workspace;
-    const contractDirectory = getPathByPlatform(workspace);
+    let folderPath: string;
+
+    if (folderUri === undefined) {
+      const truffleWorkspace = await getTruffleWorkspace();
```
Comment (michaeljohnbennett) [inline src/commands/TruffleCommands.ts:209]: this is good overall, is there room to think about making this more generic in terms of workspace? as part of the SDK Core Commands the concept of a workspace is in there v's a hard function?

**Review by michaeljohnbennett — APPROVED** [review]

File: src/commands/TruffleCommands.ts (hunk 1 above)
Comment (acuarica) [reply src/commands/TruffleCommands.ts:209]: Maybe we could reuse some parts of the Truffle SDK into the, let's say, HardHat SDK. But first I guess we need to define some sort of common denominator functionality to add the SDK Core Commands. Then see how we can implement it.
